# Creates jira tickets for new github issues to help triage
name: Jira Issue Creator TEST

on:
  issues:
    types: [opened]
  workflow_call:
    inputs:
      label:
        required: true
        type: string

env:
  JIRA_TAG: TS

jobs:
  call-workflow-passing-data:
    uses: amplitude/Amplitude-TypeScript/.github/workflows/jira-issue-create.yml@github-template
    with:
      label: "Flutter"
      secrets: inherit
