# Creates jira tickets for new github issues to help triage
name: Jira Issue Creator TEST

on:
  issues:
    types: [opened]
  workflow_call:
    inputs:
      label:
        type: string

jobs:
  call-workflow-passing-data:
    uses: yuhao900914/Amplitude-Flutter-Example/.github/workflows/jira_create_issue_template.yml@main
    secrets:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      JIRA_PROJECT: ${{ secrets.JIRA_PROJECT }}
