# Creates jira tickets for new github issues to help triage
name: Jira Issue Creator TEST

on:
  issues:
    types: [opened]
  workflow_call:
    inputs:
      label:
        required: true
        type: string
env:
  JIRA_TAG: TS

jobs:
  build:
    runs-on: ubuntu-18.04
    environment: Jira
    name: SDK Bot Jira Issue Creation
    steps:
      - name: TEST 
        run: echo "$JIRA_TAG"
